import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Header} from "../components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "sebastien-fernandez.fr",
  description: "Generated by create next app - site vitrine",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
